package bar.cxf.client.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-09T16:42:44.059+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://service.cxf.foo/", name = "OrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processOrder", targetNamespace = "http://service.cxf.foo/", className = "bar.cxf.client.wsdl.ProcessOrder")
    @WebMethod
    @ResponseWrapper(localName = "processOrderResponse", targetNamespace = "http://service.cxf.foo/", className = "bar.cxf.client.wsdl.ProcessOrderResponse")
    public bar.cxf.client.wsdl.ApplicationResponse processOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        bar.cxf.client.wsdl.Order arg0
    );
}
