package bar.cxf.client.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-09T16:42:44.114+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "OrderServiceImplService", 
                  wsdlLocation = "http://localhost:8080/cxf/foo/OrderProcess?wsdl",
                  targetNamespace = "http://service.cxf.foo/") 
public class OrderServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.cxf.foo/", "OrderServiceImplService");
    public final static QName OrderServiceImplPort = new QName("http://service.cxf.foo/", "OrderServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxf/foo/OrderProcess?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxf/foo/OrderProcess?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServiceImplPort")
    public OrderService getOrderServiceImplPort() {
        return super.getPort(OrderServiceImplPort, OrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServiceImplPort")
    public OrderService getOrderServiceImplPort(WebServiceFeature... features) {
        return super.getPort(OrderServiceImplPort, OrderService.class, features);
    }

}
